export {default as Navbar} from './Navbar'
export {default as HomePage} from './HomePage'
export {default as CryptoCurrencies} from './CryptoCurrencies'
export {default as CryptoDetail} from './CryptoDetail'
export {default as News} from './News'
export {default as Exchanges} from './Exchanges'